//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace NV.DetectionPlatform.Entity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“Entities”部分中的连接字符串初始化新 Entities 对象。
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 Entities 对象。
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Product> Product
        {
            get
            {
                if ((_Product == null))
                {
                    _Product = base.CreateObjectSet<Product>("Product");
                }
                return _Product;
            }
        }
        private ObjectSet<Product> _Product;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ExamParam> ExamParam
        {
            get
            {
                if ((_ExamParam == null))
                {
                    _ExamParam = base.CreateObjectSet<ExamParam>("ExamParam");
                }
                return _ExamParam;
            }
        }
        private ObjectSet<ExamParam> _ExamParam;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ImageParam> ImageParam
        {
            get
            {
                if ((_ImageParam == null))
                {
                    _ImageParam = base.CreateObjectSet<ImageParam>("ImageParam");
                }
                return _ImageParam;
            }
        }
        private ObjectSet<ImageParam> _ImageParam;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Overlay> Overlay
        {
            get
            {
                if ((_Overlay == null))
                {
                    _Overlay = base.CreateObjectSet<Overlay>("Overlay");
                }
                return _Overlay;
            }
        }
        private ObjectSet<Overlay> _Overlay;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AOIParam> AOIParam
        {
            get
            {
                if ((_AOIParam == null))
                {
                    _AOIParam = base.CreateObjectSet<AOIParam>("AOIParam");
                }
                return _AOIParam;
            }
        }
        private ObjectSet<AOIParam> _AOIParam;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<USMParam> USMParamSet
        {
            get
            {
                if ((_USMParamSet == null))
                {
                    _USMParamSet = base.CreateObjectSet<USMParam>("USMParamSet");
                }
                return _USMParamSet;
            }
        }
        private ObjectSet<USMParam> _USMParamSet;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Product EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
    
        /// <summary>
        /// 用于向 ExamParam EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToExamParam(ExamParam examParam)
        {
            base.AddObject("ExamParam", examParam);
        }
    
        /// <summary>
        /// 用于向 ImageParam EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToImageParam(ImageParam imageParam)
        {
            base.AddObject("ImageParam", imageParam);
        }
    
        /// <summary>
        /// 用于向 Overlay EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOverlay(Overlay overlay)
        {
            base.AddObject("Overlay", overlay);
        }
    
        /// <summary>
        /// 用于向 AOIParam EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAOIParam(AOIParam aOIParam)
        {
            base.AddObject("AOIParam", aOIParam);
        }
    
        /// <summary>
        /// 用于向 USMParamSet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUSMParamSet(USMParam uSMParam)
        {
            base.AddObject("USMParamSet", uSMParam);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="AOIParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AOIParam : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 AOIParam 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static AOIParam CreateAOIParam(global::System.String gUID)
        {
            AOIParam aOIParam = new AOIParam();
            aOIParam.GUID = gUID;
            return aOIParam;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpperlimitofBubble
        {
            get
            {
                return _UpperlimitofBubble;
            }
            set
            {
                OnUpperlimitofBubbleChanging(value);
                ReportPropertyChanging("UpperlimitofBubble");
                _UpperlimitofBubble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpperlimitofBubble");
                OnUpperlimitofBubbleChanged();
            }
        }
        private Nullable<global::System.Int32> _UpperlimitofBubble;
        partial void OnUpperlimitofBubbleChanging(Nullable<global::System.Int32> value);
        partial void OnUpperlimitofBubbleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LowerlimitofBubble
        {
            get
            {
                return _LowerlimitofBubble;
            }
            set
            {
                OnLowerlimitofBubbleChanging(value);
                ReportPropertyChanging("LowerlimitofBubble");
                _LowerlimitofBubble = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LowerlimitofBubble");
                OnLowerlimitofBubbleChanged();
            }
        }
        private Nullable<global::System.Int32> _LowerlimitofBubble;
        partial void OnLowerlimitofBubbleChanging(Nullable<global::System.Int32> value);
        partial void OnLowerlimitofBubbleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PercentofBubblePass
        {
            get
            {
                return _PercentofBubblePass;
            }
            set
            {
                OnPercentofBubblePassChanging(value);
                ReportPropertyChanging("PercentofBubblePass");
                _PercentofBubblePass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PercentofBubblePass");
                OnPercentofBubblePassChanged();
            }
        }
        private Nullable<global::System.Int32> _PercentofBubblePass;
        partial void OnPercentofBubblePassChanging(Nullable<global::System.Int32> value);
        partial void OnPercentofBubblePassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ExamParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExamParam : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ExamParam 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static ExamParam CreateExamParam(global::System.String gUID)
        {
            ExamParam examParam = new ExamParam();
            examParam.GUID = gUID;
            return examParam;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> KV
        {
            get
            {
                return _KV;
            }
            set
            {
                OnKVChanging(value);
                ReportPropertyChanging("KV");
                _KV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KV");
                OnKVChanged();
            }
        }
        private Nullable<global::System.Double> _KV;
        partial void OnKVChanging(Nullable<global::System.Double> value);
        partial void OnKVChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UA
        {
            get
            {
                return _UA;
            }
            set
            {
                OnUAChanging(value);
                ReportPropertyChanging("UA");
                _UA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UA");
                OnUAChanged();
            }
        }
        private Nullable<global::System.Int32> _UA;
        partial void OnUAChanging(Nullable<global::System.Int32> value);
        partial void OnUAChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.Double> _Time;
        partial void OnTimeChanging(Nullable<global::System.Double> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fps
        {
            get
            {
                return _Fps;
            }
            set
            {
                OnFpsChanging(value);
                ReportPropertyChanging("Fps");
                _Fps = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fps");
                OnFpsChanged();
            }
        }
        private Nullable<global::System.Int32> _Fps;
        partial void OnFpsChanging(Nullable<global::System.Int32> value);
        partial void OnFpsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                OnProductTypeChanging(value);
                ReportPropertyChanging("ProductType");
                _ProductType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductType");
                OnProductTypeChanged();
            }
        }
        private global::System.String _ProductType;
        partial void OnProductTypeChanging(global::System.String value);
        partial void OnProductTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FILA
        {
            get
            {
                return _FILA;
            }
            set
            {
                OnFILAChanging(value);
                ReportPropertyChanging("FILA");
                _FILA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FILA");
                OnFILAChanged();
            }
        }
        private Nullable<global::System.Int32> _FILA;
        partial void OnFILAChanging(Nullable<global::System.Int32> value);
        partial void OnFILAChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PREH
        {
            get
            {
                return _PREH;
            }
            set
            {
                OnPREHChanging(value);
                ReportPropertyChanging("PREH");
                _PREH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PREH");
                OnPREHChanged();
            }
        }
        private Nullable<global::System.Int32> _PREH;
        partial void OnPREHChanging(Nullable<global::System.Int32> value);
        partial void OnPREHChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ImageParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageParam : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ImageParam 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static ImageParam CreateImageParam(global::System.String gUID)
        {
            ImageParam imageParam = new ImageParam();
            imageParam.GUID = gUID;
            return imageParam;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WindowWidth
        {
            get
            {
                return _WindowWidth;
            }
            set
            {
                OnWindowWidthChanging(value);
                ReportPropertyChanging("WindowWidth");
                _WindowWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WindowWidth");
                OnWindowWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _WindowWidth;
        partial void OnWindowWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWindowWidthChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WindowLevel
        {
            get
            {
                return _WindowLevel;
            }
            set
            {
                OnWindowLevelChanging(value);
                ReportPropertyChanging("WindowLevel");
                _WindowLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WindowLevel");
                OnWindowLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _WindowLevel;
        partial void OnWindowLevelChanging(Nullable<global::System.Int32> value);
        partial void OnWindowLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Gamma
        {
            get
            {
                return _Gamma;
            }
            set
            {
                OnGammaChanging(value);
                ReportPropertyChanging("Gamma");
                _Gamma = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gamma");
                OnGammaChanged();
            }
        }
        private Nullable<global::System.Double> _Gamma;
        partial void OnGammaChanging(Nullable<global::System.Double> value);
        partial void OnGammaChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SharpLevel
        {
            get
            {
                return _SharpLevel;
            }
            set
            {
                OnSharpLevelChanging(value);
                ReportPropertyChanging("SharpLevel");
                _SharpLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SharpLevel");
                OnSharpLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _SharpLevel;
        partial void OnSharpLevelChanging(Nullable<global::System.Int32> value);
        partial void OnSharpLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReduceNoiseLevel
        {
            get
            {
                return _ReduceNoiseLevel;
            }
            set
            {
                OnReduceNoiseLevelChanging(value);
                ReportPropertyChanging("ReduceNoiseLevel");
                _ReduceNoiseLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReduceNoiseLevel");
                OnReduceNoiseLevelChanged();
            }
        }
        private Nullable<global::System.Int32> _ReduceNoiseLevel;
        partial void OnReduceNoiseLevelChanging(Nullable<global::System.Int32> value);
        partial void OnReduceNoiseLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FalseColor
        {
            get
            {
                return _FalseColor;
            }
            set
            {
                OnFalseColorChanging(value);
                ReportPropertyChanging("FalseColor");
                _FalseColor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FalseColor");
                OnFalseColorChanged();
            }
        }
        private Nullable<global::System.Boolean> _FalseColor;
        partial void OnFalseColorChanging(Nullable<global::System.Boolean> value);
        partial void OnFalseColorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EqualHist
        {
            get
            {
                return _EqualHist;
            }
            set
            {
                OnEqualHistChanging(value);
                ReportPropertyChanging("EqualHist");
                _EqualHist = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EqualHist");
                OnEqualHistChanged();
            }
        }
        private Nullable<global::System.Boolean> _EqualHist;
        partial void OnEqualHistChanging(Nullable<global::System.Boolean> value);
        partial void OnEqualHistChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                OnProductTypeChanging(value);
                ReportPropertyChanging("ProductType");
                _ProductType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductType");
                OnProductTypeChanged();
            }
        }
        private global::System.String _ProductType;
        partial void OnProductTypeChanging(global::System.String value);
        partial void OnProductTypeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Overlay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Overlay : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Overlay 对象。
        /// </summary>
        /// <param name="overlayID">OverlayID 属性的初始值。</param>
        public static Overlay CreateOverlay(global::System.Int32 overlayID)
        {
            Overlay overlay = new Overlay();
            overlay.OverlayID = overlayID;
            return overlay;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverlayDesc
        {
            get
            {
                return _OverlayDesc;
            }
            set
            {
                OnOverlayDescChanging(value);
                ReportPropertyChanging("OverlayDesc");
                _OverlayDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OverlayDesc");
                OnOverlayDescChanged();
            }
        }
        private global::System.String _OverlayDesc;
        partial void OnOverlayDescChanging(global::System.String value);
        partial void OnOverlayDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TagGroup
        {
            get
            {
                return _TagGroup;
            }
            set
            {
                OnTagGroupChanging(value);
                ReportPropertyChanging("TagGroup");
                _TagGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TagGroup");
                OnTagGroupChanged();
            }
        }
        private global::System.String _TagGroup;
        partial void OnTagGroupChanging(global::System.String value);
        partial void OnTagGroupChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TagElement
        {
            get
            {
                return _TagElement;
            }
            set
            {
                OnTagElementChanging(value);
                ReportPropertyChanging("TagElement");
                _TagElement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TagElement");
                OnTagElementChanged();
            }
        }
        private global::System.String _TagElement;
        partial void OnTagElementChanging(global::System.String value);
        partial void OnTagElementChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayFormat
        {
            get
            {
                return _DisplayFormat;
            }
            set
            {
                OnDisplayFormatChanging(value);
                ReportPropertyChanging("DisplayFormat");
                _DisplayFormat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayFormat");
                OnDisplayFormatChanged();
            }
        }
        private global::System.String _DisplayFormat;
        partial void OnDisplayFormatChanging(global::System.String value);
        partial void OnDisplayFormatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OverlayID
        {
            get
            {
                return _OverlayID;
            }
            set
            {
                if (_OverlayID != value)
                {
                    OnOverlayIDChanging(value);
                    ReportPropertyChanging("OverlayID");
                    _OverlayID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OverlayID");
                    OnOverlayIDChanged();
                }
            }
        }
        private global::System.Int32 _OverlayID;
        partial void OnOverlayIDChanging(global::System.Int32 value);
        partial void OnOverlayIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsUseful
        {
            get
            {
                return _IsUseful;
            }
            set
            {
                OnIsUsefulChanging(value);
                ReportPropertyChanging("IsUseful");
                _IsUseful = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUseful");
                OnIsUsefulChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsUseful;
        partial void OnIsUsefulChanging(Nullable<global::System.Boolean> value);
        partial void OnIsUsefulChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Product 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static Product CreateProduct(global::System.String gUID)
        {
            Product product = new Product();
            product.GUID = gUID;
            return product;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductTypeID
        {
            get
            {
                return _ProductTypeID;
            }
            set
            {
                OnProductTypeIDChanging(value);
                ReportPropertyChanging("ProductTypeID");
                _ProductTypeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductTypeID");
                OnProductTypeIDChanged();
            }
        }
        private global::System.String _ProductTypeID;
        partial void OnProductTypeIDChanging(global::System.String value);
        partial void OnProductTypeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductSpecification
        {
            get
            {
                return _ProductSpecification;
            }
            set
            {
                OnProductSpecificationChanging(value);
                ReportPropertyChanging("ProductSpecification");
                _ProductSpecification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductSpecification");
                OnProductSpecificationChanged();
            }
        }
        private global::System.String _ProductSpecification;
        partial void OnProductSpecificationChanging(global::System.String value);
        partial void OnProductSpecificationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductKeywords
        {
            get
            {
                return _ProductKeywords;
            }
            set
            {
                OnProductKeywordsChanging(value);
                ReportPropertyChanging("ProductKeywords");
                _ProductKeywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductKeywords");
                OnProductKeywordsChanged();
            }
        }
        private global::System.String _ProductKeywords;
        partial void OnProductKeywordsChanging(global::System.String value);
        partial void OnProductKeywordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private global::System.String _StartTime;
        partial void OnStartTimeChanging(global::System.String value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.String _EndTime;
        partial void OnEndTimeChanging(global::System.String value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageFolder
        {
            get
            {
                return _ImageFolder;
            }
            set
            {
                OnImageFolderChanging(value);
                ReportPropertyChanging("ImageFolder");
                _ImageFolder = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageFolder");
                OnImageFolderChanged();
            }
        }
        private global::System.String _ImageFolder;
        partial void OnImageFolderChanging(global::System.String value);
        partial void OnImageFolderChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="USMParam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USMParam : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 USMParam 对象。
        /// </summary>
        /// <param name="gUID">GUID 属性的初始值。</param>
        public static USMParam CreateUSMParam(global::System.String gUID)
        {
            USMParam uSMParam = new USMParam();
            uSMParam.GUID = gUID;
            return uSMParam;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                if (_GUID != value)
                {
                    OnGUIDChanging(value);
                    ReportPropertyChanging("GUID");
                    _GUID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GUID");
                    OnGUIDChanged();
                }
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Int32> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Int32> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Radius
        {
            get
            {
                return _Radius;
            }
            set
            {
                OnRadiusChanging(value);
                ReportPropertyChanging("Radius");
                _Radius = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Radius");
                OnRadiusChanged();
            }
        }
        private Nullable<global::System.Int32> _Radius;
        partial void OnRadiusChanging(Nullable<global::System.Int32> value);
        partial void OnRadiusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Threshold
        {
            get
            {
                return _Threshold;
            }
            set
            {
                OnThresholdChanging(value);
                ReportPropertyChanging("Threshold");
                _Threshold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Threshold");
                OnThresholdChanged();
            }
        }
        private Nullable<global::System.Int32> _Threshold;
        partial void OnThresholdChanging(Nullable<global::System.Int32> value);
        partial void OnThresholdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }

    #endregion

    
}
